# Helix theme: Rose Pine Moon with Monaspace font styling
# Author: Custom configuration for Monaspace
#
# NOTE: Helix inherits fonts from your terminal emulator (Ghostty).
# For Monaspace's multi-family support, configure Ghostty to use different
# Monaspace families for different contexts (e.g., Radon for italic, Neon for regular).
# This theme file controls colors (Rose Pine Moon palette) and text modifiers (bold/italic).

# Syntax highlighting
"comment" = { fg = "muted", modifiers = ["italic"] }
"comment.line" = { fg = "muted", modifiers = ["italic"] }
"comment.block" = { fg = "muted", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "muted", modifiers = ["italic"] }

"constant" = { fg = "foam" }
"constant.builtin" = { fg = "foam" }
"constant.builtin.boolean" = { fg = "rose" }
"constant.character" = { fg = "gold" }
"constant.character.escape" = { fg = "subtle" }
"constant.numeric" = { fg = "gold" }

"constructor" = { fg = "foam" }

"function" = { fg = "rose" }
"function.builtin" = { fg = "rose", modifiers = ["bold"] }
"function.method" = { fg = "rose" }
"function.macro" = { fg = "iris", modifiers = ["bold"] }
"function.special" = { fg = "foam" }

"keyword" = { fg = "pine", modifiers = ["bold"] }
"keyword.control" = { fg = "pine", modifiers = ["bold"] }
"keyword.control.conditional" = { fg = "pine", modifiers = ["bold"] }
"keyword.control.repeat" = { fg = "pine", modifiers = ["bold"] }
"keyword.control.return" = { fg = "pine", modifiers = ["bold"] }
"keyword.control.import" = { fg = "pine", modifiers = ["bold"] }
"keyword.control.exception" = { fg = "pine", modifiers = ["bold"] }
"keyword.operator" = { fg = "subtle" }
"keyword.directive" = { fg = "iris", modifiers = ["bold"] }
"keyword.function" = { fg = "pine", modifiers = ["bold"] }
"keyword.storage" = { fg = "pine" }
"keyword.storage.type" = { fg = "pine" }
"keyword.storage.modifier" = { fg = "pine" }

"label" = { fg = "iris" }

"namespace" = { fg = "foam" }

"operator" = { fg = "subtle" }

"punctuation" = { fg = "subtle" }
"punctuation.delimiter" = { fg = "subtle" }
"punctuation.bracket" = { fg = "subtle" }
"punctuation.special" = { fg = "foam" }

"string" = { fg = "gold" }
"string.regexp" = { fg = "foam" }
"string.special" = { fg = "foam" }
"string.special.path" = { fg = "gold" }
"string.special.url" = { fg = "foam" }
"string.special.symbol" = { fg = "iris" }

"tag" = { fg = "foam" }
"tag.builtin" = { fg = "rose" }

"type" = { fg = "foam", modifiers = ["italic"] }
"type.builtin" = { fg = "foam", modifiers = ["italic"] }
"type.enum" = { fg = "foam", modifiers = ["italic"] }
"type.enum.variant" = { fg = "foam", modifiers = ["italic"] }

"variable" = { fg = "text" }
"variable.builtin" = { fg = "love", modifiers = ["bold"] }
"variable.parameter" = { fg = "iris", modifiers = ["italic"] }
"variable.other.member" = { fg = "foam" }

"attribute" = { fg = "iris" }

# Markup (Markdown, etc.)
"markup.heading" = { fg = "rose", modifiers = ["bold"] }
"markup.heading.marker" = { fg = "muted" }
"markup.heading.1" = { fg = "rose", modifiers = ["bold"] }
"markup.heading.2" = { fg = "foam", modifiers = ["bold"] }
"markup.heading.3" = { fg = "iris", modifiers = ["bold"] }
"markup.heading.4" = { fg = "gold", modifiers = ["bold"] }
"markup.heading.5" = { fg = "pine", modifiers = ["bold"] }
"markup.heading.6" = { fg = "love", modifiers = ["bold"] }

"markup.list" = { fg = "subtle" }
"markup.list.unnumbered" = { fg = "subtle" }
"markup.list.numbered" = { fg = "subtle" }
"markup.list.checked" = { fg = "foam" }
"markup.list.unchecked" = { fg = "muted" }

"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }

"markup.link.url" = { fg = "foam", modifiers = ["underlined"] }
"markup.link.text" = { fg = "rose" }
"markup.link.label" = { fg = "iris" }

"markup.quote" = { fg = "muted", modifiers = ["italic"] }

"markup.raw.inline" = { fg = "gold" }
"markup.raw.block" = { fg = "gold" }

# Diff
"diff.plus" = { fg = "foam" }
"diff.plus.gutter" = { fg = "foam" }
"diff.minus" = { fg = "love" }
"diff.minus.gutter" = { fg = "love" }
"diff.delta" = { fg = "gold" }
"diff.delta.gutter" = { fg = "gold" }

# UI
"ui.background" = { bg = "base" }
"ui.background.separator" = { fg = "overlay" }

"ui.cursor" = { bg = "highlight-high", fg = "base" }
"ui.cursor.normal" = { bg = "highlight-high", fg = "base" }
"ui.cursor.insert" = { bg = "foam", fg = "base" }
"ui.cursor.select" = { bg = "rose", fg = "base" }
"ui.cursor.match" = { bg = "overlay", fg = "text" }
"ui.cursor.primary" = { bg = "iris", fg = "base" }
"ui.cursor.primary.normal" = { bg = "iris", fg = "base" }
"ui.cursor.primary.insert" = { bg = "foam", fg = "base" }
"ui.cursor.primary.select" = { bg = "rose", fg = "base" }

"ui.cursorline.primary" = { bg = "surface" }

"ui.gutter" = { bg = "base" }
"ui.gutter.selected" = { bg = "surface" }

"ui.linenr" = { fg = "muted" }
"ui.linenr.selected" = { fg = "iris", modifiers = ["bold"] }

"ui.statusline" = { fg = "subtle", bg = "surface" }
"ui.statusline.inactive" = { fg = "muted", bg = "surface" }
"ui.statusline.normal" = { fg = "base", bg = "rose" }
"ui.statusline.insert" = { fg = "base", bg = "foam" }
"ui.statusline.select" = { fg = "base", bg = "iris" }

"ui.popup" = { fg = "text", bg = "overlay" }
"ui.popup.info" = { fg = "text", bg = "overlay" }

"ui.window" = { fg = "overlay" }

"ui.help" = { fg = "text", bg = "overlay" }

"ui.text" = { fg = "text" }
"ui.text.focus" = { fg = "foam", modifiers = ["bold"] }
"ui.text.inactive" = { fg = "muted" }
"ui.text.info" = { fg = "text", bg = "overlay" }

"ui.virtual.ruler" = { bg = "overlay" }
"ui.virtual.whitespace" = { fg = "highlight-med" }
"ui.virtual.indent-guide" = { fg = "overlay" }
"ui.virtual.inlay-hint" = { fg = "muted" }

"ui.menu" = { fg = "text", bg = "overlay" }
"ui.menu.selected" = { fg = "base", bg = "foam", modifiers = ["bold"] }
"ui.menu.scroll" = { fg = "subtle", bg = "surface" }

"ui.selection" = { bg = "highlight-med" }
"ui.selection.primary" = { bg = "highlight-high" }

"ui.highlight" = { bg = "highlight-med" }

# Diagnostics
"diagnostic.error" = { underline = { color = "love", style = "curl" }, modifiers = ["bold"] }
"diagnostic.warning" = { underline = { color = "gold", style = "curl" }, modifiers = ["bold"] }
"diagnostic.info" = { underline = { color = "foam", style = "curl" }, modifiers = ["italic"] }
"diagnostic.hint" = { underline = { color = "iris", style = "curl" }, modifiers = ["italic"] }
"diagnostic.unnecessary" = { fg = "muted" }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

"error" = { fg = "love" }
"warning" = { fg = "gold" }
"info" = { fg = "foam" }
"hint" = { fg = "iris" }

# Rose Pine Moon color palette
[palette]
base = "#232136"
surface = "#2a273f"
overlay = "#393552"
muted = "#6e6a86"
subtle = "#908caa"
text = "#e0def4"
love = "#eb6f92"
gold = "#f6c177"
rose = "#ea9a97"
pine = "#3e8fb0"
foam = "#9ccfd8"
iris = "#c4a7e7"
highlight-low = "#2a283e"
highlight-med = "#44415a"
highlight-high = "#56526e"
